[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "hindent"  # Name of your Python module/package
author = "Grant Smith"
author-email = "14.gsmith.14@example.com"
home-page = "https://github.com/GSmithApps/hindent"
